### ISSUE TITLE
Decode giving empty array buffer

### ISSUE THREAD

**Issue by ishwarrimal** [niklasvh/base64-arraybuffer#10]
Hi,

encode method for buffer is giving me base64 strng.. But reverse is not happening.
Its giving me empty ArrayBuffer.

Am I doing anything wrong?

Here is my code

`var b64toBuff = require('base64-arraybuffer');`
`let data = fs.readFileSync(imagePath);`
`let c = b64toBuff.encode(data);`
`let d = b64toBuff.decode(c)`

c gives me a base64 string.
But d gives me empty ArrayBuffer{}

**Comment by machester4** [comment]
if you debug whit `console.log(d)` you get empty array, use `console.log(d.byteLength)`
