### ISSUE TITLE
Encode in C# and decode with javascript

### ISSUE THREAD

**Issue by hesampour** [niklasvh/base64-arraybuffer#19]
I want to Encode my file in C# to base64 and decode it with this module in my Ionic App
I use this code to Encode in C# but it seems not get the true file in my Client when I decode it:

`
Byte[] bytes = File.ReadAllBytes(localFilePath);
String file = Convert.ToBase64String(bytes); 
`

**Comment by programando-ideas** [comment]
Maybe you forgot to put data "image/jpeg;base64," in javascript before base64 string?
